builds:
  -
    id: "azcopy"
    binary: azcopy
    ldflags:
      - -extldflags=-static -s -w -X main.build={{.Version}} 

    goos:
      - linux
      #- windows
      #- darwin

    goarch:
      - amd64
      #- arm64

    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  -
    format_overrides:
      - goos: windows
        format: zip

universal_binaries:
- replace: true

before:
  hooks:
  - go mod tidy
