builds:
  -
    id: "azcopy"
    binary: azcopy

    env:
    # Resolves a requirement for alpine/scratch to include glibc
    - CGO_ENABLED=0

    goos:
      - linux
      #- windows
      #- darwin

    goarch:
      - amd64
      #- arm64

    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  -
    format_overrides:
      - goos: windows
        format: zip

universal_binaries:
- replace: true

before:
  hooks:
  - go mod tidy
